name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # or main, depending on your default branch
  pull_request:
    branches:
      - master  # or main, depending on your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 17 with Adoptium Temurin
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'  # Use 'temurin' as the distribution name
          check-latest: false

      # Build the project with Maven
      - name: Build with Maven
        run: mvn clean install

      # Run the tests
      - name: Run Tests
        run: mvn test
