name: Java CI/CD on Local Machine

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (Java Development Kit)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # Step 3: Install dependencies and build
      - name: Build with Maven
        run: mvn clean install

      # Step 4: Run unit tests
      - name: Run Tests
        run: mvn test

      # Optional: Run the Spring Boot application (only for testing, not for CI)
      - name: Run Application Locally
        run: mvn spring-boot:run
        if: ${{ github.event_name == 'push' }} # Only run for pushes
