name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # or main, based on your branch
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adoptopenjdk'
          check-latest: false

      # Add your build and test steps here
      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test
